export const CATEGORY_REPOSITORY = "CATEGORY_REPOSITORY";
export const COMMENT_REPOSITORY = "COMMENT_REPOSITORY";
export const POST_REPOSITORY = "POST_REPOSITORY";
export const REVIEW_REPOSITORY = "REVIEW_REPOSITORY";
export const USER_REPOSITORY = "USER_REPOSITORY";
export const UPLOAD_REPOSITORY = "UPLOAD_REPOSITORY";
export const ERROR_LOGGER = "ERROR_LOGGER";
export const INFO_LOGGER = "INFO_LOGGER";