name: buckbuck API

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build --if-present

      - name: Testing env setup
        env:
          TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
          TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          touch .env
          echo DB_HOST=$TEST_DB_HOST >> .env
          echo DB_USER=$TEST_DB_USER >> .env
          echo DB_PASSWORD=$TEST_DB_PASSWORD >> .env
          echo DB_NAME=$DB_NAME >> .env
          echo JWT_SECRET_KEY=$JWT_SECRET_KEY >> .env

      - name: Run unit test
        id: unit-test
        run: npm run test:unit

      - name: whoami test
        if: success()
        run: whoami

      - name: test success
        if: steps.unit-test.outcome == 'success'
        run: |
          echo "성공"

      - name: test fail
        if: steps.unit-test.outcome != 'success'
        run: exit 1