name: buckbuck API

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build --if-present

      - name: Testing env setup
        env:
          TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
          TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          touch .env
          echo DB_HOST=$TEST_DB_HOST >> .env
          echo DB_USER=$TEST_DB_USER >> .env
          echo DB_PASSWORD=$TEST_DB_PASSWORD >> .env
          echo DB_NAME=$DB_NAME >> .env
          echo JWT_SECRET_KEY=$JWT_SECRET_KEY >> .env

      - name: Run test
        run: |
          npm test > test_result.json
          if grep '"numFailedTests":0' test_result.json; then
            ${{ secrets.TEST_SUCCESS_WEBHOOK }}
            echo "테스트 성공"
          else
            ${{ secrets.TEST_FAIL_WEBHOOK }}
            echo "테스트 실패케이스 존재"
            exit 1
          fi

      - name: check result file
        run: cat test_result.json

      - name: whoami
        run: whoami