name: buckbuck API

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: install dependencies
        run: npm install

      - name: run E2E Test
        run: npm run test:e2e

      - name: run Unit Test
        run: npm run test:unit

      - name: run ls -al
        if: ${{ success() }}
        run: ls -al