name: buckbuck API

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build --if-present

      - name: Testing env setup
        run: |
          touch .env.local
          echo "${{ secrets.ENV }}" >> .env.local

      - name: Run test
        run: |
          npm test
          rm -rfv .env.local

      - name: Product env setup
        run: |
          touch .env.product
          echo "${{ secrets.PRODUCT_ENV }}" >> .env.product

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: buckbuck
          IMAGE_TAG: latest
        run: |
          docker build --no-cache -t $REPOSITORY:$IMAGE_TAG .
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker rmi $(docker images -q)
            docker pull ${{ steps.login-ecr.outputs.registry }}/buckbuck:latest || true
            docker stop buckbuck
            docker rm buckbuck
            docker run -d --name buckbuck -v /var/log/buckbuck:/usr/src/app/logs -p 3000:3000 ${{ steps.login-ecr.outputs.registry }}/buckbuck:latest
            docker stop buckbuck-sub
            docker rm buckbuck-sub
            docker run -d --name buckbuck-sub -v /var/log/buckbuck:/usr/src/app/logs -p 3001:3001 ${{ steps.login-ecr.outputs.registry }}/buckbuck:latest
            ${{ secrets.DEPLOY_SUCCESS_HOOK }}